<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" EnableEventValidation="false" CodeBehind="ReportDiscrepency.aspx.cs" Inherits="SSISWebSiteApplication.StoreClerkViews.ReportDiscrepency" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <div class="jumbotron">
        <br /><br /><br /><br />
        <h2>Create Discrepancy Report
        </h2>
        </div>
        <asp:GridView ID="grdView_Reportdiscrepency" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SSIS" DataKeyNames="DiscrepancyID" EnableModelValidation="true" CssClass="table table-responsive table-striped table-hover" BorderStyle="None" BorderWidth="1px" CellPadding="4" >
            <Columns>
                <asp:BoundField DataField="DiscrepancyID" HeaderText="DiscrepancyID" SortExpression="DiscrepancyID" InsertVisible="false" ReadOnly="true" />
                <asp:BoundField DataField="InventoryID" HeaderText="InventoryID" SortExpression="InventoryID" ReadOnly="true" />
                <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" ReadOnly="true" />
                <asp:BoundField DataField="InventoryQuantity" HeaderText="InventoryQuantity" SortExpression="InventoryQuantity" ReadOnly="true" />
                <asp:BoundField DataField="ActualQuantity" HeaderText="ActualQuantity" SortExpression="ActualQuantity" />
                <asp:BoundField DataField="DiscrepancyReason" HeaderText="DiscrepancyReason" SortExpression="DiscrepancyReason" />
            </Columns>
        </asp:GridView>
        <asp:SqlDataSource ID="SSIS" runat="server" ConnectionString="<%$ ConnectionStrings:SSISDbModelContext %>" SelectCommand="SELECT [DiscrepancyID], [InventoryID], [Price], [InventoryQuantity], [ActualQuantity], [DiscrepancyReason] FROM [DiscrepancyDetail]" UpdateCommand="UPDATE [DiscrepancyDetail] Set [ActualQuantity]=@ActualQuantity, [DiscrepancyReason]=@DiscrepancyReason Where [DiscrepancyID]=@DiscrepancyID" DeleteCommand="DELETE from [DiscrepancyDetail] Where [DiscrepancyID]=@DiscrepancyID"></asp:SqlDataSource>
        <br />
        <br />
        <br />
        <asp:Button ID="btn_Generate" runat="server" Text="Generate" OnClick="btn_Generate_Click" OnClientClick="target ='_blank';" />

            <br />

    


</asp:Content>

